"""PDF reports. Kept separate from the blueprints so any screen can reuse a builder."""
from io import BytesIO

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

from app.timeutil import to_eat

INK = colors.HexColor("#111827")
LINE = colors.HexColor("#e5e7eb")
ZEBRA = colors.HexColor("#f9fafb")


def build_farmer_transactions_pdf(factory_name, farmer, transactions, start, end):
    """A farmer's tea-delivery transactions between start and end (dates), as PDF bytes."""
    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer, pagesize=A4, title="Tea delivery transactions",
        topMargin=18 * mm, bottomMargin=18 * mm, leftMargin=16 * mm, rightMargin=16 * mm,
    )
    styles = getSampleStyleSheet()

    story = [
        Paragraph(factory_name, styles["Title"]),
        Paragraph("Tea delivery transactions", styles["Heading2"]),
        Paragraph(f"{farmer.full_name} &nbsp;&middot;&nbsp; {farmer.farmer_number} "
                  f"&nbsp;&middot;&nbsp; {farmer.buying_centre.name}", styles["Normal"]),
        Paragraph(f"{start.strftime('%d %b %Y')} &ndash; {end.strftime('%d %b %Y')}", styles["Normal"]),
        Spacer(1, 8 * mm),
    ]

    rows = [["When", "Transaction", "Centre", "Kilos", "Status"]]
    valid_total = 0.0
    for t in transactions:
        if t.status == "VALID":
            valid_total += t.weight_kg
        rows.append([
            to_eat(t.transaction_time).strftime("%d %b %Y, %H:%M"),
            t.transaction_number,
            t.buying_centre.name,
            f"{t.weight_kg:.1f}",
            "Voided" if t.status == "VOIDED" else "Valid",
        ])
    if len(rows) == 1:
        rows.append(["No tea delivered in this period.", "", "", "", ""])

    table = Table(rows, colWidths=[36 * mm, 32 * mm, 38 * mm, 20 * mm, 22 * mm], repeatRows=1)
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), INK),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("ALIGN", (3, 0), (3, -1), "RIGHT"),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("GRID", (0, 0), (-1, -1), 0.4, LINE),
       
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
    ]))
    story.append(table)
    story.append(Spacer(1, 6 * mm))
    story.append(Paragraph(f"Valid kilos in this period: <b>{valid_total:.1f} kg</b>", styles["Normal"]))

    doc.build(story)
    return buffer.getvalue()


def build_insights_report_pdf(factory_name, generated_by, start, end, centre_name, clerk_name, report):
    """The Insights & Trends report: totals per buying centre and per clerk for a
    From/To window, as PDF bytes. `generated_by` is the User who requested it —
    the report always names them and their department, since more than one role
    can open this page. `report` is app.analytics.report_data(...)'s return value."""
    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer, pagesize=A4, title="Insights & Trends report",
        topMargin=18 * mm, bottomMargin=18 * mm, leftMargin=16 * mm, rightMargin=16 * mm,
    )
    styles = getSampleStyleSheet()

    story = [
        Paragraph(factory_name, styles["Title"]),
        Paragraph("Insights &amp; Trends report", styles["Heading2"]),
        Paragraph(f"{start.strftime('%d %b %Y')} &ndash; {end.strftime('%d %b %Y')}"
                  f"{' &nbsp;&middot;&nbsp; ' + centre_name if centre_name else ''}"
                  f"{' &nbsp;&middot;&nbsp; Clerk: ' + clerk_name if clerk_name else ''}", styles["Normal"]),
        Paragraph(f"Generated by {generated_by.full_name} &nbsp;&middot;&nbsp; {generated_by.department.name}",
                  styles["Normal"]),
        Spacer(1, 8 * mm),
        Paragraph(f"Total kilos: <b>{report['total_kg']:.1f} kg</b> across {report['count']} transaction(s)",
                  styles["Normal"]),
        Spacer(1, 6 * mm),
    ]

    def _table(title, rows):
        section = [Paragraph(title, styles["Heading3"])]
        body = [["Name", "Kilos", "Transactions"]]
        for row in rows:
            body.append([row["name"], f"{row['kg']:.1f}", str(row["count"])])
        if len(body) == 1:
            body.append(["No records in this period.", "", ""])
        table = Table(body, colWidths=[90 * mm, 40 * mm, 40 * mm], repeatRows=1)
        table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), INK),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("ALIGN", (1, 0), (2, -1), "RIGHT"),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("GRID", (0, 0), (-1, -1), 0.4, LINE),
           
            ("TOPPADDING", (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ]))
        section.append(table)
        section.append(Spacer(1, 8 * mm))
        return section

    story += _table("By buying centre", [
        {"name": r["centre"].name, "kg": r["kg"], "count": r["count"]} for r in report["centre_rows"]
    ])
    story += _table("By clerk", [
        {"name": r["clerk"].full_name, "kg": r["kg"], "count": r["count"]} for r in report["clerk_rows"]
    ])

    # The full list of individual transactions the search matched — not just the
    # centre/clerk rollups above.
    story.append(Paragraph("Transactions in this search", styles["Heading3"]))
    tx_rows = [["When", "Transaction", "Centre", "Farmer", "Kilos", "Clerk", "Status"]]
    for t in report["transactions"]:
        tx_rows.append([
            to_eat(t.transaction_time).strftime("%d %b %Y, %H:%M"),
            t.transaction_number,
            t.buying_centre.name,
            t.farmer.full_name,
            f"{t.weight_kg:.1f}",
            t.clerk.full_name,
            "Voided" if t.status == "VOIDED" else "Valid",
        ])
    if len(tx_rows) == 1:
        tx_rows.append(["No transactions in this search.", "", "", "", "", "", ""])
    #tx_table = Table(tx_rows, colWidths=[28 * mm, 24 * mm, 24 * mm, 30 * mm, 16 * mm, 26 * mm, 22 * mm], repeatRows=1)

    tx_table = Table(
    tx_rows,
    colWidths=[
        30 * mm,  # When
        33 * mm,  # Transaction
        35 * mm,  # Centre
        33 * mm,  # Farmer
        10 * mm,  # Kilos
        30 * mm,  # Clerk
        15 * mm,  # Status
    ],
    repeatRows=1
    )
    tx_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), INK),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
        ("FONTSIZE", (0, 0), (-1, -1), 7.5),
        ("ALIGN", (4, 0), (4, -1), "RIGHT"),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("GRID", (0, 0), (-1, -1), 0.4, LINE),
     
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]))
    story.append(tx_table)

    doc.build(story)
    return buffer.getvalue()
